=== wol101/useful_tools/PrimateAgents/data/primate_simulation.dtd
<!ELEMENT PRIMATE_SIMULATION (
    GLOBAL, 
    DISPLAY, 
    AGENT*,
    ENVIRONMENT
    )
>

<!ELEMENT ENVIRONMENT (
    DAY_LENGTH, 
    HABITAT_TYPE*, 
    GRID,
    GRID_SQUARE*
    )
>

<!ELEMENT GLOBAL EMPTY>
<!ATTLIST GLOBAL 
    STARTTIME CDATA #REQUIRED
    ENDTIME CDATA #REQUIRED
    STEPTIME NMTOKEN #REQUIRED
    PROPORTIONTOWINVOTE NMTOKEN #REQUIRED
    AGENTSUMMARIESONLY NMTOKEN #REQUIRED
    GRIDSQUARETOTALSONLY NMTOKEN #REQUIRED
>
    
<!ELEMENT DISPLAY EMPTY>
<!ATTLIST DISPLAY 
    WINDOWSIZE NMTOKENS #REQUIRED
    DAYTIMESPEEDUP NMTOKEN #REQUIRED
    NIGHTTIMESPEEDUP NMTOKEN #REQUIRED
    KEYORIGIN NMTOKENS #REQUIRED
    KEYSIZE NMTOKENS #REQUIRED
    KEYTEXTSIZE NMTOKEN #REQUIRED
>

<!ELEMENT AGENT EMPTY>
<!ATTLIST AGENT 
    AGENTNAME CDATA #REQUIRED
    AGENTMULTIPLIER NMTOKEN #REQUIRED
    COMFORTABLESPEED NMTOKEN #REQUIRED
    RESTPOWER NMTOKEN #REQUIRED
    MOVEPOWER NMTOKEN #REQUIRED
    SOCIALPOWER NMTOKEN #REQUIRED
    FORAGEPOWER NMTOKEN #REQUIRED
    SEARCHRADIUS NMTOKEN #REQUIRED
    DAILYNOMINALENERGYBUDGET NMTOKEN #REQUIRED
    DAILYNOMINALSOCIALTIME NMTOKEN #REQUIRED
    NOMINALTIMEBETWEENDRINKING NMTOKEN #REQUIRED
    RELATIVEFOODIMPORTANCE NMTOKEN #REQUIRED
    RELATIVESOCIALIMPORTANCE NMTOKEN #REQUIRED
    RELATIVEDRINKINGIMPORTANCE NMTOKEN #REQUIRED
    FORAGINGMOVETHRESHOLD NMTOKEN #REQUIRED
    SOCIALISINGMOVETHRESHOLD NMTOKEN #REQUIRED
    RESTINGMOVETHRESHOLD NMTOKEN #REQUIRED
    RESTSOCIALRISKTHRESHOLD NMTOKEN #REQUIRED
>

<!ELEMENT DAY_LENGTH EMPTY>
<!ATTLIST DAY_LENGTH 
    VALUE NMTOKENS #REQUIRED
>

<!ELEMENT HABITAT_TYPE EMPTY>
<!ATTLIST HABITAT_TYPE 
    NAME ID #REQUIRED
    VISIBILITY NMTOKENS #REQUIRED
    PRODUCTIVITY NMTOKENS #REQUIRED
    FORAGINGRATEFACTOR NMTOKENS #REQUIRED
    FORAGINGMODEL NMTOKEN #REQUIRED
    MOVEFORAGINGRATEPENALTY NMTOKENS #REQUIRED
    RECOVERYRATE NMTOKENS #REQUIRED
    MEANENERGYVALUE NMTOKENS #REQUIRED
    MAPCOLOUR NMTOKENS #REQUIRED
    FULLRESOURCE NMTOKEN #REQUIRED
>

<!ELEMENT GRID EMPTY>
<!ATTLIST GRID 
    XSIZE NMTOKEN #REQUIRED
    YSIZE NMTOKEN #REQUIRED
    XORIGIN NMTOKEN #REQUIRED
    YORIGIN NMTOKEN #REQUIRED
>

<!ELEMENT GRID_SQUARE EMPTY>
<!ATTLIST GRID_SQUARE 
    XGRID NMTOKEN #REQUIRED
    YGRID NMTOKEN #REQUIRED
    HABITAT_TYPE NMTOKENS #REQUIRED
    MEAN_GROUND_SLOPE NMTOKEN #REQUIRED
    SLEEPING_SITE NMTOKEN #IMPLIED
    CLIFF_REFUGE NMTOKEN #IMPLIED
    OTHER_REFUGE NMTOKEN #IMPLIED
    WATER_PRESENT NMTOKEN #IMPLIED
>

=== wol101/useful_tools/PrimateAgents/data/MonteCarloData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PRIMATE_SIMULATION SYSTEM "primate_simulation.dtd">

<PRIMATE_SIMULATION>

<!-- Parameters controlling the simulation -->
<!-- Currently have data from June to end of December
     which is 13046400 to 31536000 seconds -->
<!--
GLOBAL section sets the parameters that control the simulator

STARTTIME             the date that the simulation starts 00:00 on DD/MM/YYYY
ENDTIME               the date that the simulation ends 00:00 on DD/MM/YYYY
STEPTIME              the time in seconds that is added for each simulation cycle
PROPORTIONTOWINVOTE   the fraction of the total population that need to vote to move
AGENTSUMMARIESONLY    if non-zero only output summaries of agent activity
GRIDSQUARETOTALSONLY  if non-zero only output the number of squares entered rather than individual occupancy

Note. Votes currently counted by category, so more that PROPORTIONTOWINVOTE must all vote
to move for the same reason.
-->

<GLOBAL
    STARTTIME="01/06/1998"
    ENDTIME="01/01/1999"
    STEPTIME="300.0"
    PROPORTIONTOWINVOTE="MC_PROPORTIONTOWINVOTE"
    AGENTSUMMARIESONLY="1"
    GRIDSQUARETOTALSONLY="1"
/>    


<!--
DISPLAY section sets how the graphic display works. It does not effect the numerical
outcome of the simulation.

WINDOWSIZE           Size of main window at startup
DAYTIMESPEEDUP       Number of steps to skip at day time (only effects display)
NIGHTTIMESPEEDUP     Number of steps to skip at night time (only effects display)
KEYORIGIN            Position of key "X Y"
KEYSIZE              Size of key "Width Height"
KEYTEXTSIZE          Size of text in key

Note: WINDOWSIZE is mapped onto a 1.0 by 1.0 space using the smallest dimension. The display
will always show this 1.0 by 1.0 square but any additional space depends on the aspect ratio
of the window.
-->

<DISPLAY
    WINDOWSIZE="600 600"
    DAYTIMESPEEDUP="1"
    NIGHTTIMESPEEDUP="10"
    KEYORIGIN="0.625 0.025"
    KEYSIZE="0.35 0.6"
    KEYTEXTSIZE="0.01"
/>

<!--
AGENT section sets the modelling parameters for each agent. Each agent can have its own
AGENT section, or a multiple agents can be defined with a single (or several) AGENT sections.
So for example males and females, or different age classes could each have their own AGENT
section and the AGENTMULTIPLIER is used to set the number of time the AGENT is duplicated.

AGENTNAME                   Name of this class of agent
AGENTMULTIPLIER             Number of individuals in this agent class
COMFORTABLESPEED            Normal movement speed (m/s)
RESTPOWER                   Rate of energy use when resting (W)
MOVEPOWER                   Rate of energy use when moving at COMFORTABLESPEED (W)
SOCIALPOWER                 Rate of energy use when socialising (W)
FORAGEPOWER                 Rate of energy use when foraging (W)
SEARCHRADIUS                Distance to look for best social and foraging sites
DAILYNOMINALENERGYBUDGET    Estimated daily energy budget (J)
Note: This value is only used to calculate the slope of the energy desire function since the
goal state is to maintain energy balance.
DAILYNOMINALSOCIALTIME      The desired amount of socialising wanted (s)
NOMINALTIMEBETWEENDRINKING  The maximum amount of time between drinking bouts (s)
RELATIVEFOODIMPORTANCE      The normalised importance score for food
Note: the accuracy of this value depends on DAILYNOMINALENERGYBUDGET being a reasonable estimate.
RELATIVESOCIALIMPORTANCE    The normalised importance score for socialising
RELATIVEDRINKINGIMPORTANCE  The normalised importance score for drinking
FORAGINGMOVETHRESHOLD       This is how much better the foraging rate in another grid square within SEARCHRADIUS needs to be before the agent will want to move
SOCIALISINGMOVETHRESHOLD    This is how much better for socialising another grid square within SEARCHRADIUS needs to be before the agent will want to move
RESTINGMOVETHRESHOLD        This is how much better for resting another grid square within SEARCHRADIUS needs to be before the agent will want to move
RESTSOCIALRISKTHRESHOLD     The agent will only rest or socialise if the risk is lower than this threshold
-->

<AGENT
    AGENTNAME="Female Baboon"
    AGENTMULTIPLIER="40"
    COMFORTABLESPEED="0.5"
    RESTPOWER="34.63"
    MOVEPOWER="50.59"
    SOCIALPOWER="64.04"
    FORAGEPOWER="36.71"
    SEARCHRADIUS="MC_SEARCHRADIUS"
    DAILYNOMINALENERGYBUDGET="3500000.0"
    DAILYNOMINALSOCIALTIME="7200.0"
    NOMINALTIMEBETWEENDRINKING="86400.0"
    RELATIVEFOODIMPORTANCE="MC_RELATIVEFOODIMPORTANCE"
    RELATIVESOCIALIMPORTANCE="MC_RELATIVESOCIALIMPORTANCE"
    RELATIVEDRINKINGIMPORTANCE="MC_RELATIVEDRINKINGIMPORTANCE"
    FORAGINGMOVETHRESHOLD="MC_FORAGINGMOVETHRESHOLD"
    SOCIALISINGMOVETHRESHOLD="MC_SOCIALISINGMOVETHRESHOLD"
    RESTINGMOVETHRESHOLD="MC_RESTINGMOVETHRESHOLD"
    RESTSOCIALRISKTHRESHOLD="MC_RESTSOCIALRISKTHRESHOLD"
/>

<!--
The ENVIRONMENT section includes all the specification details for the environment
-->

<ENVIRONMENT>

<!-- 
DAY_LENGTH specifies the day length parameters

VALUE      12 monthly values of day length in hours
-->

<DAY_LENGTH
    VALUE="14.16 13.35 12.32 11.25 10.35 9.9 10.01 10.84 11.85 12.93 13.89 14.42"
/>

<!-- 
HABITAT_TYPE information specific to a particular habitat type

NAME                      This is the label that is used to identify habitat types for grid squares. It cannot contain whitespace.
VISIBILITY                12 monthly visibility distance in metres
PRODUCTIVITY              12 monthly productivity values in grams dry weight per square metre

FORAGINGMODEL             PROPORTION
FORAGINGRATEFACTOR        12 monthly foraging rate factors: proportion of total grid square contents eaten by a single agent in 1 second
FORAGINGMODEL             FIXEDRATE
FORAGINGRATEFACTOR        12 monthly foraging rate factors: number of grams of food eaten by a single agent in 1 second - independent of amount of food available as long as it is over zero

MOVEFORAGINGRATEPENALTY   12 monthly foraging rate penality factors: ie how much less food is obtained for foraging whilst moving
RECOVERYRATE              12 monthly food recovery rates (grams / m2 / day)
MEANENERGYVALUE           12 monthly energy values of 1g dry weight of food (J)
MAPCOLOUR                 "Red Green Blue" value to use when displaying map
FULLRESOURCE              Value in g/m2 to show as a full square
-->

<!-- 
Note there is very little BURNT_ACACIA_WOODLAND on grid so:
currently using BURNT_FYNBOS recovery rate for BURNT_ACACIA_WOODLAND
-->

<HABITAT_TYPE
    NAME="BURNT_ACACIA_WOODLAND"
    VISIBILITY="20.8 20.8 20.8 20.8 20.8 20.8 20.8 20.8 20.8 20.8 20.8 20.8"
    PRODUCTIVITY="0 0 0 0 0 0.002 0.001 0.016 0.013 0.008 0.006 0.001"
    FORAGINGMODEL="FIXEDRATE"
    FORAGINGRATEFACTOR="0 0 0 0 0 0.0293 0.0294 0.03 0.029 0.0275 0.025 0.03"
    MOVEFORAGINGRATEPENALTY="0 0 0 0 0 0.718 1.000 0.780 0.455 0.064 0.000 0.000"
    RECOVERYRATE="0 0 0 0 0 0.000033 0.00023 0 0 0 0 0"
    MEANENERGYVALUE="13980 13980 13980 13980 13980 13980 13980 13980 13980 13980 13980 13980"
    MAPCOLOUR="68 68 68"
    FULLRESOURCE="2"
/>    

<HABITAT_TYPE
    NAME="CLIMAX_FYNBOS"
    VISIBILITY="13.7 13.7 13.7 13.7 13.7 13.7 13.7 13.7 13.7 13.7 13.7 13.7"
    PRODUCTIVITY="0 0 0 0 0 0.012 1.008 1.309 0.851 0.335 0.205 0.229"
    FORAGINGMODEL="FIXEDRATE"
    FORAGINGRATEFACTOR="0 0 0 0 0 0.0305 0.0306 0.0308 0.0305 0.0312 0.0306 0.031"
    MOVEFORAGINGRATEPENALTY="0 0 0 0 0 0.211 0.434 0.278 0.328 0.162 0.068 1.000"
    RECOVERYRATE="0 0 0 0 0 0.0332 0.021616 0.01003 0 0 0 0"
    MEANENERGYVALUE="13980 13980 13980 13980 13980 13980 13980 13980 13980 13980 13980 13980"
    MAPCOLOUR="247 209 164"
    FULLRESOURCE="2"
/>    

<HABITAT_TYPE
    NAME="GRASSLAND"
    VISIBILITY="129.7 129.7 129.7 129.7 129.7 129.7 129.7 129.7 129.7 129.7 129.7 129.7 "
    PRODUCTIVITY="0 0 0 0 0 0.487 0.985 1.572 0.988 2.254 1.431 1.083"
    FORAGINGMODEL="FIXEDRATE"
    FORAGINGRATEFACTOR="0 0 0 0 0 0.03 0.03 0.03 0.0296 0.0295 0.0299 0.0304"
    MOVEFORAGINGRATEPENALTY="0 0 0 0 0 0.979 0.981 0.368 0.411 0.937 0.968 1.000"
    RECOVERYRATE="0 0 0 0 0 0.0166 0.03616 0.01956 0.01136 0.0422 0 0"
    MEANENERGYVALUE="13980 13980 13980 13980 13980 13980 13980 13980 13980 13980 13980 13980"
    MAPCOLOUR="226 150 98"
    FULLRESOURCE="2"
/>    

<HABITAT_TYPE
    NAME="BURNT_FYNBOS"
    VISIBILITY="35.8 35.8 35.8 35.8 35.8 35.8 35.8 35.8 35.8 35.8 35.8 35.8 "
    PRODUCTIVITY="0 0 0 0 0 0.002 0.001 0.016 0.013 0.008 0.006 0.001"
    FORAGINGMODEL="FIXEDRATE"
    FORAGINGRATEFACTOR="0 0 0 0 0 0.0293 0.0294 0.03 0.029 0.0275 0.025 0.03"
    MOVEFORAGINGRATEPENALTY="0 0 0 0 0 0.718 1.000 0.780 0.455 0.064 0.000 0.000"
    RECOVERYRATE="0 0 0 0 0 0.000033 0.00023 0 0 0 0 0"
    MEANENERGYVALUE="13980 13980 13980 13980 13980 13980 13980 13980 13980 13980 13980 13980"
    MAPCOLOUR="152 103 88"
    FULLRESOURCE="2"
/>    

<HABITAT_TYPE
    NAME="ACACIA_WOODLAND"
    VISIBILITY="4.6 4.6 4.6 4.6 4.6 4.6 4.6 4.6 4.6 4.6 4.6 4.6"
    PRODUCTIVITY="0 0 0 0 0 1.58 2.115 2.257 4.909 4.636 11.85 22.842"
    FORAGINGMODEL="FIXEDRATE"
    FORAGINGRATEFACTOR="0 0 0 0 0 0.0304 0.0312 0.0303 0.0313 0.0333 0.0343 0.0341"
    MOVEFORAGINGRATEPENALTY="0 0 0 0 0 0.633 0.574 0.475 0.461 0.150 0.129 0.081"
    RECOVERYRATE="0 0 0 0 0 0.01783 0.011283 0.001683 0.03965 0.16393 0.30343 0.3664"
    MEANENERGYVALUE="13980 13980 13980 13980 13980 13980 13980 13980 13980 13980 13980 13980"
    MAPCOLOUR="92 161 132"
    FULLRESOURCE="2"
/>    

<HABITAT_TYPE
    NAME="VLEI"
    VISIBILITY="251.7 251.7 251.7 251.7 251.7 251.7 251.7 251.7 251.7 251.7 251.7 251.7"
    PRODUCTIVITY="0 0 0 0 0 1.825 1.225 3.266 0 8.255 15.296 13.702"
    FORAGINGMODEL="FIXEDRATE"
    FORAGINGRATEFACTOR="0 0 0 0 0 0.0261 0.0268 0.028 0.0285 0.0277 0.0269 0.0262"
    MOVEFORAGINGRATEPENALTY="0 0 0 0 0 0.211 0.285 0.132 0.192 0.041 0.129 0.019"
    RECOVERYRATE="0 0 0 0 0 0 0.024016 0.02783 0.08315 0.206683 0.090783 0"
